spring:
  redis:
    lettuce:
      pool:
        max-active: 1024 #最大连接数 默认8
        max-wait: 10000  #最大连接阻塞等待时间，单位毫秒，默认-1
        max-idle: 200    #最大空闲连接，默认
        min-idle: 5      #最小空闲连接 默认0
    port: 6379
    timeout: 10000
    host: 192.168.157.129
    database: 0

lzj:
  cache:
    sendyzm:
      prefix: 'com:xxxx:login:'
    productDetails:
      prefix: 'com:xxxx:productDetails:'
      suffix: ':selectItemById'